apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres  # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
     metadata:
       labels:     
         app: postgres
     spec:
       containers:
         - name: postgres
           image: postgres:10.1  # Sets Image
           resources:
             requests:
               memory: "200Mi"
               cpu: "100m"
           ports:
             - containerPort: 5432  # Exposes container port     
           envFrom:
             - configMapRef:
                 name: postgres-config 
           volumeMounts:
             - mountPath: /var/lib/postgresql/data
               name: postgredba
       volumes:
         - name: postgredba
           persistentVolumeClaim:
             claimName: postgresql-data-claim
